"""Care actions: the agent proposes, the clinician approves, the database executes.

A care coordinator agent may write one thing: a proposed action for its own
patient (a lab request, a message to the patient, a follow-up visit). A trigger
forces the status to `proposed` and stamps who proposed it; row-level security
with update_check refuses a proposal for any other patient. The agent has no
UPDATE grant and no EXECUTE grant, so it cannot approve or execute anything.

The clinician's identity, DA_CLINICIAN, holds EXECUTE on DECIDE_CARE_ACTION and
SELECT on the workflow tables, nothing else. The procedure (definer rights)
approves or rejects a proposal, then executes an approved one in the same
transaction: a lab_order, a patient_message in a simulated portal outbox, or an
appointment request. Every transition is written to care_action_event.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05
"""

from alembic import op

from common.config import PATIENT_KEYS, agent_user

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None

CLINICIAN = "DA_CLINICIAN"
NEW_TABLES = ("CARE_ACTION", "CARE_ACTION_EVENT", "LAB_ORDER", "PATIENT_MESSAGE")

DDL = [
    """CREATE TABLE care_action (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         patient_id VARCHAR2(16) NOT NULL REFERENCES patient(patient_id),
         run_id VARCHAR2(64),
         kind VARCHAR2(32) NOT NULL CHECK (kind IN ('lab_request', 'patient_message', 'follow_up')),
         status VARCHAR2(16) DEFAULT 'proposed' NOT NULL CHECK (status IN ('proposed', 'approved', 'executed', 'rejected')),
         title VARCHAR2(256) NOT NULL,
         rationale VARCHAR2(2000) NOT NULL,
         citations VARCHAR2(1000),
         payload JSON NOT NULL,
         proposed_by VARCHAR2(128),
         created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
         decided_by VARCHAR2(128),
         decided_at TIMESTAMP,
         result_table VARCHAR2(64),
         result_id NUMBER,
         result_summary VARCHAR2(400))""",
    """CREATE TABLE care_action_event (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         action_id NUMBER NOT NULL REFERENCES care_action(id),
         patient_id VARCHAR2(16) NOT NULL,
         status VARCHAR2(16) NOT NULL,
         actor VARCHAR2(128) NOT NULL,
         at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
         note VARCHAR2(1000))""",
    """CREATE TABLE lab_order (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         patient_id VARCHAR2(16) NOT NULL REFERENCES patient(patient_id),
         action_id NUMBER REFERENCES care_action(id),
         tests JSON NOT NULL,
         urgency VARCHAR2(32),
         reason VARCHAR2(2000),
         status VARCHAR2(32) DEFAULT 'ordered' NOT NULL,
         ordered_by VARCHAR2(128),
         ordered_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)""",
    """CREATE TABLE patient_message (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         patient_id VARCHAR2(16) NOT NULL REFERENCES patient(patient_id),
         action_id NUMBER REFERENCES care_action(id),
         channel VARCHAR2(64) DEFAULT 'portal (simulated)' NOT NULL,
         subject VARCHAR2(256) NOT NULL,
         body VARCHAR2(4000) NOT NULL,
         status VARCHAR2(32) DEFAULT 'queued' NOT NULL,
         queued_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)""",
    "CREATE INDEX ix_care_action_patient ON care_action (patient_id, created_at)",
    "CREATE INDEX ix_care_action_event_action ON care_action_event (action_id)",
]

# Agents can only propose: the status and the proposer are not theirs to set.
TRIGGER_PROPOSE = """
CREATE OR REPLACE TRIGGER trg_care_action_propose
BEFORE INSERT ON care_action FOR EACH ROW
BEGIN
  :NEW.status := 'proposed';
  :NEW.proposed_by := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.created_at := SYSTIMESTAMP;
  :NEW.decided_by := NULL; :NEW.decided_at := NULL;
  :NEW.result_table := NULL; :NEW.result_id := NULL; :NEW.result_summary := NULL;
END;
"""
TRIGGER_AUDIT = """
CREATE OR REPLACE TRIGGER trg_care_action_audit
AFTER INSERT ON care_action FOR EACH ROW
BEGIN
  INSERT INTO care_action_event (action_id, patient_id, status, actor, note)
  VALUES (:NEW.id, :NEW.patient_id, 'proposed', :NEW.proposed_by, 'drafted by the care coordinator agent');
END;
"""

PROCEDURE = """
CREATE OR REPLACE PROCEDURE decide_care_action(
  p_id IN NUMBER, p_decision IN VARCHAR2, p_payload IN CLOB DEFAULT NULL, p_note IN VARCHAR2 DEFAULT NULL)
AUTHID DEFINER AS
  v_actor  VARCHAR2(128) := SYS_CONTEXT('USERENV', 'SESSION_USER');
  v_row    care_action%ROWTYPE;
  v_new_id NUMBER;
  v_summary VARCHAR2(400);
BEGIN
  SELECT * INTO v_row FROM care_action WHERE id = p_id FOR UPDATE;
  IF v_row.status <> 'proposed' THEN
    RAISE_APPLICATION_ERROR(-20010, 'care action ' || p_id || ' is ' || v_row.status || ', not proposed');
  END IF;

  IF p_decision = 'reject' THEN
    UPDATE care_action SET status = 'rejected', decided_by = v_actor, decided_at = SYSTIMESTAMP WHERE id = p_id;
    INSERT INTO care_action_event (action_id, patient_id, status, actor, note)
    VALUES (p_id, v_row.patient_id, 'rejected', v_actor, p_note);
    COMMIT;
    RETURN;
  ELSIF p_decision <> 'approve' THEN
    RAISE_APPLICATION_ERROR(-20011, 'decision must be approve or reject');
  END IF;

  IF p_payload IS NOT NULL THEN
    UPDATE care_action SET payload = JSON(p_payload) WHERE id = p_id;
    v_row.payload := JSON(p_payload);
  END IF;
  UPDATE care_action SET status = 'approved', decided_by = v_actor, decided_at = SYSTIMESTAMP WHERE id = p_id;
  INSERT INTO care_action_event (action_id, patient_id, status, actor, note)
  VALUES (p_id, v_row.patient_id, 'approved', v_actor, NVL(p_note, 'approved in the web application'));

  IF v_row.kind = 'lab_request' THEN
    INSERT INTO lab_order (patient_id, action_id, tests, urgency, reason, ordered_by)
    VALUES (v_row.patient_id, p_id, JSON_QUERY(v_row.payload, '$.tests' RETURNING CLOB),
            JSON_VALUE(v_row.payload, '$.urgency'), v_row.rationale, v_actor)
    RETURNING id INTO v_new_id;
    v_summary := 'lab_order ' || v_new_id || ' ordered: '
                 || JSON_QUERY(v_row.payload, '$.tests' RETURNING VARCHAR2(300));
    UPDATE care_action SET result_table = 'LAB_ORDER', result_id = v_new_id, result_summary = v_summary WHERE id = p_id;
  ELSIF v_row.kind = 'patient_message' THEN
    INSERT INTO patient_message (patient_id, action_id, subject, body)
    VALUES (v_row.patient_id, p_id, JSON_VALUE(v_row.payload, '$.subject'),
            JSON_VALUE(v_row.payload, '$.body' RETURNING VARCHAR2(4000)))
    RETURNING id INTO v_new_id;
    v_summary := 'patient_message ' || v_new_id || ' queued to the portal outbox (simulated)';
    UPDATE care_action SET result_table = 'PATIENT_MESSAGE', result_id = v_new_id, result_summary = v_summary WHERE id = p_id;
  ELSE
    INSERT INTO appointment (patient_id, scheduled_for, kind, status)
    VALUES (v_row.patient_id,
            TRUNC(SYSDATE) + NVL(TO_NUMBER(JSON_VALUE(v_row.payload, '$.within_days')), 14),
            NVL(JSON_VALUE(v_row.payload, '$.visit_type'), 'Follow-up visit'), 'requested')
    RETURNING id INTO v_new_id;
    v_summary := 'appointment ' || v_new_id || ' requested within '
                 || NVL(JSON_VALUE(v_row.payload, '$.within_days'), '14') || ' days';
    UPDATE care_action SET result_table = 'APPOINTMENT', result_id = v_new_id, result_summary = v_summary WHERE id = p_id;
  END IF;

  UPDATE care_action SET status = 'executed' WHERE id = p_id;
  INSERT INTO care_action_event (action_id, patient_id, status, actor, note)
  VALUES (p_id, v_row.patient_id, 'executed', 'database: DECIDE_CARE_ACTION', v_summary);
  COMMIT;
END;
"""

# The scope function gains the clinician: a clinician's panel sees every patient.
SCOPE = """
CREATE OR REPLACE FUNCTION DA_PATIENT_SCOPE(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2 AS
  v_user VARCHAR2(128) := SYS_CONTEXT('USERENV', 'SESSION_USER');
  v_col  VARCHAR2(64)  := CASE WHEN p_object = 'PATIENT_NOTE_VEC'
                               THEN 'JSON_VALUE(metadata, ''$.patient_id'')'
                               ELSE 'patient_id' END;
BEGIN
  IF v_user IN ('DA_OWNER', 'DA_CLINICIAN') THEN
    RETURN '1=1';
  ELSIF REGEXP_LIKE(v_user, '^DA_AGENT_[A-Z]$') THEN
    RETURN v_col || ' = ''SYN-' || SUBSTR(v_user, -1) || '''';
  END IF;
  RETURN '1=0';
END;
"""


def _policy(table: str) -> str:
    return f"""
BEGIN
  DBMS_RLS.ADD_POLICY(object_schema => 'DA_OWNER', object_name => '{table}',
    policy_name => 'DA_SCOPE_{table}', function_schema => 'DA_OWNER',
    policy_function => 'DA_PATIENT_SCOPE', statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check => TRUE);
END;
"""


def _raw(sql: str) -> None:
    # PL/SQL bodies use :NEW, which SQLAlchemy would read as a bind parameter.
    op.get_bind().exec_driver_sql(sql)


def upgrade() -> None:
    for sql in DDL:
        _raw(sql)
    _raw(TRIGGER_PROPOSE)
    _raw(TRIGGER_AUDIT)
    _raw(PROCEDURE)
    _raw(SCOPE)
    for table in NEW_TABLES:
        op.execute(_policy(table))
    for key in PATIENT_KEYS:
        user = agent_user(key)
        op.execute(f"GRANT SELECT, INSERT ON care_action TO {user}")
        op.execute(f"GRANT SELECT ON care_action_event TO {user}")
    for table in (*NEW_TABLES, "PATIENT", "APPOINTMENT"):
        op.execute(f"GRANT SELECT ON {table} TO {CLINICIAN}")
    op.execute(f"GRANT EXECUTE ON decide_care_action TO {CLINICIAN}")


def downgrade() -> None:
    for table in NEW_TABLES:
        op.execute(f"BEGIN DBMS_RLS.DROP_POLICY('DA_OWNER', '{table}', 'DA_SCOPE_{table}'); END;")
    op.execute("DROP PROCEDURE decide_care_action")
    for table in ("PATIENT_MESSAGE", "LAB_ORDER", "CARE_ACTION_EVENT", "CARE_ACTION"):
        op.execute(f"DROP TABLE {table} PURGE")
