"""Agent-level policy and agent-to-agent escalation.

Every care-action tool stamps its database session with the name of the agent
that called it (CLIENT_IDENTIFIER, set by tool code, not by the model). Policy
CP-03 says only the medication-safety agent may propose a medication change:
when the care coordinator tries, the proposal trigger refuses the insert
(ORA-20014), logs the refusal in policy_event through an autonomous
transaction, and tells the caller to escalate. The coordinator then writes an
agent_escalation addressed to the medication-safety agent, which reviews it
and proposes the change itself; CP-02 still sends that proposal to a doctor.

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05
"""

from alembic import op

from common.config import PATIENT_KEYS, agent_user

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None

DDL = [
    "ALTER TABLE care_policy ADD (allowed_proposer VARCHAR2(64) DEFAULT 'any' NOT NULL)",
    "UPDATE care_policy SET allowed_proposer = 'medication-safety' WHERE kind = 'medication_change'",
    """INSERT INTO care_policy (code, kind, required_role, rule_text, allowed_proposer)
       VALUES ('CP-03', 'agent_scope', 'physician',
               'Only the medication-safety agent may propose a medication change; the care coordinator must escalate to it. The doctor still decides (CP-02).',
               'medication-safety')""",
    "ALTER TABLE care_action ADD (proposed_agent VARCHAR2(64), escalation_id NUMBER)",
    """CREATE TABLE agent_escalation (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         patient_id VARCHAR2(16) NOT NULL REFERENCES patient(patient_id),
         run_id VARCHAR2(64),
         from_agent VARCHAR2(64) NOT NULL,
         to_agent VARCHAR2(64) NOT NULL CHECK (to_agent IN ('medication-safety')),
         policy_code VARCHAR2(16),
         subject VARCHAR2(256) NOT NULL,
         reason VARCHAR2(2000) NOT NULL,
         citations VARCHAR2(1000),
         status VARCHAR2(16) DEFAULT 'open' NOT NULL CHECK (status IN ('open', 'accepted', 'declined')),
         resolution VARCHAR2(2000),
         action_id NUMBER,
         created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
         resolved_at TIMESTAMP)""",
    """CREATE TABLE policy_event (
         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         patient_id VARCHAR2(16),
         run_id VARCHAR2(64),
         agent VARCHAR2(64),
         policy_code VARCHAR2(16),
         decision VARCHAR2(16) NOT NULL,
         detail VARCHAR2(1000),
         at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)""",
]

LOG = """
CREATE OR REPLACE PROCEDURE log_policy_event(
  p_patient IN VARCHAR2, p_run IN VARCHAR2, p_agent IN VARCHAR2, p_code IN VARCHAR2,
  p_decision IN VARCHAR2, p_detail IN VARCHAR2) AUTHID DEFINER AS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO policy_event (patient_id, run_id, agent, policy_code, decision, detail)
  VALUES (p_patient, p_run, p_agent, p_code, p_decision, p_detail);
  COMMIT;
END;
"""

TRIGGER_PROPOSE = """
CREATE OR REPLACE TRIGGER trg_care_action_propose
BEFORE INSERT ON care_action FOR EACH ROW
DECLARE
  v_code     care_policy.code%TYPE;
  v_role     care_policy.required_role%TYPE;
  v_proposer care_policy.allowed_proposer%TYPE;
  v_agent    VARCHAR2(64) := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'unknown');
BEGIN
  SELECT code, required_role, allowed_proposer INTO v_code, v_role, v_proposer
    FROM care_policy WHERE kind = :NEW.kind;
  IF v_proposer <> 'any' AND v_agent <> v_proposer THEN
    log_policy_event(:NEW.patient_id, :NEW.run_id, v_agent, 'CP-03', 'refused',
      v_agent || ' may not propose a ' || :NEW.kind || ' (' || :NEW.title || '); escalate to the ' || v_proposer || ' agent');
    RAISE_APPLICATION_ERROR(-20014, 'policy CP-03: the ' || v_agent || ' agent may not propose a ' || :NEW.kind
      || '; escalate it to the ' || v_proposer || ' agent with escalate_to_agent');
  END IF;
  :NEW.policy_code := v_code;
  :NEW.required_role := v_role;
  :NEW.proposed_agent := v_agent;
  :NEW.status := CASE WHEN v_role = 'physician' THEN 'needs_physician' ELSE 'proposed' END;
  :NEW.proposed_by := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.created_at := SYSTIMESTAMP;
  :NEW.decided_by := NULL; :NEW.decided_at := NULL;
  :NEW.result_table := NULL; :NEW.result_id := NULL; :NEW.result_summary := NULL;
END;
"""

TRIGGER_AUDIT = """
CREATE OR REPLACE TRIGGER trg_care_action_audit
AFTER INSERT ON care_action FOR EACH ROW
BEGIN
  INSERT INTO care_action_event (action_id, patient_id, status, actor, note)
  VALUES (:NEW.id, :NEW.patient_id, 'proposed', :NEW.proposed_by || ' (' || :NEW.proposed_agent || ')',
          CASE WHEN :NEW.escalation_id IS NOT NULL
               THEN 'proposed by the ' || :NEW.proposed_agent || ' agent on escalation #' || :NEW.escalation_id
               ELSE 'drafted by the ' || :NEW.proposed_agent || ' agent' END);
  IF :NEW.status = 'needs_physician' THEN
    INSERT INTO care_action_event (action_id, patient_id, status, actor, note)
    VALUES (:NEW.id, :NEW.patient_id, 'needs_physician', 'policy ' || :NEW.policy_code,
            'policy ' || :NEW.policy_code || ': medication changes require a physician; escalated for doctor approval');
  END IF;
END;
"""

TRIGGER_ESCALATION = """
CREATE OR REPLACE TRIGGER trg_escalation_stamp
BEFORE INSERT ON agent_escalation FOR EACH ROW
BEGIN
  :NEW.from_agent := NVL(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'unknown');
  :NEW.status := 'open';
  :NEW.created_at := SYSTIMESTAMP;
  :NEW.resolution := NULL; :NEW.action_id := NULL; :NEW.resolved_at := NULL;
  log_policy_event(:NEW.patient_id, :NEW.run_id, :NEW.from_agent, :NEW.policy_code, 'escalated',
    'escalated to the ' || :NEW.to_agent || ' agent: ' || :NEW.subject);
END;
"""


def _policy(table: str) -> str:
    return f"""
BEGIN
  DBMS_RLS.ADD_POLICY(object_schema => 'DA_OWNER', object_name => '{table}',
    policy_name => 'DA_SCOPE_{table}', function_schema => 'DA_OWNER',
    policy_function => 'DA_PATIENT_SCOPE', statement_types => 'SELECT,INSERT,UPDATE,DELETE',
    update_check => TRUE);
END;
"""


def _raw(sql: str) -> None:
    op.get_bind().exec_driver_sql(sql)


def upgrade() -> None:
    for sql in DDL:
        _raw(sql)
    _raw(LOG)
    _raw(TRIGGER_PROPOSE)
    _raw(TRIGGER_AUDIT)
    _raw(TRIGGER_ESCALATION)
    for table in ("AGENT_ESCALATION", "POLICY_EVENT"):
        _raw(_policy(table))
    for key in PATIENT_KEYS:
        user = agent_user(key)
        _raw(f"GRANT SELECT, INSERT ON agent_escalation TO {user}")
        _raw(f"GRANT UPDATE (status, resolution, action_id, resolved_at) ON agent_escalation TO {user}")
        _raw(f"GRANT SELECT ON policy_event TO {user}")
    for who in ("DA_CLINICIAN", "DA_PHYSICIAN"):
        _raw(f"GRANT SELECT ON agent_escalation TO {who}")
        _raw(f"GRANT SELECT ON policy_event TO {who}")


def downgrade() -> None:
    for table in ("AGENT_ESCALATION", "POLICY_EVENT"):
        _raw(f"BEGIN DBMS_RLS.DROP_POLICY('DA_OWNER', '{table}', 'DA_SCOPE_{table}'); END;")
    _raw("DROP TRIGGER trg_escalation_stamp")
    _raw("DROP PROCEDURE log_policy_event")
    _raw("DROP TABLE policy_event PURGE")
    _raw("DROP TABLE agent_escalation PURGE")
    _raw("ALTER TABLE care_action DROP (proposed_agent, escalation_id)")
    _raw("DELETE FROM care_policy WHERE code = 'CP-03'")
    _raw("ALTER TABLE care_policy DROP COLUMN allowed_proposer")
